---

- name: Set Test ID
  set_fact:
    test_id: '1.4.2'
  delegate_to: localhost

- name: "{{ test_id }}.check"
  shell: |
    cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1 || exit 0
    [[ $(crm_attribute -t crm_config -G -n concurrent-fencing --quiet) = "{{ expected[test_id] }}" ]] && exit 0
    exit 1
  check_mode: no
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when:  config_updated.rc > 1

- block:
    - import_role:
        name: post-results
  vars:
    status: "{{ config_updated is not changed }}"
  when:
    - ansible_check_mode

