---

name: 1.1.4
group: Corosync
labels: generic
description: |
  Corosync `join` is set to `{{ expected[name] }}`
remediation: |
  ## Remediation
  Adjust the Corosync `join` parameter as recommended by the Azure best practices.

  ## References
  AZURE:

    - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#install-the-cluster

  AWS:

    - https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-example-for-etccorosynccorosync-conf

  GCP:

    - https://cloud.google.com/solutions/sap/docs/sap-hana-ha-config-sles

  SUSE / KVM:

    - https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-example-for-etccorosynccorosync-conf

implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# Test data
key_name: join

# check id. This value must not be changed over the life of this check
id: 24ABCB
