---

- name: Set Test ID
  set_fact:
    test_id: '1.2.1'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.2"
    test_name: "Pacemaker"
    test_desc: "Fencing is enabled {{ expected[test_id] }}"
    test_remediation: "ansible"

- name: "{{ test_id }}.remediate"
  shell: 'crm configure property stonith-enabled=true'
  register: config_updated

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is changed | ternary ('Failed','Passed') }}"

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is changed | ternary ('Failed','Passed') }}"
