---

expected:
  "1.1.1": "5000"
  "1.1.2": "6000"
  "1.1.3": "20"
  "1.1.4": "60"
  "1.1.5": "10"
  "1.1.6": "udpu"
  "1.1.7": "2"
  "1.1.8": "1"
  "1.2.1": "true"
  "1.2.2.sbd": ""
  "1.2.2.fence_azure_arm": ""
  "1.3.1": "yes"
  "1.3.2": "always"
  "1.3.4": "1"
  "1.3.5": "5"
  "1.3.6": "10"
  "1.4.1.monitor_interval": ""
  "1.4.1.monitor_timeout": ""
  "1.4.1.pcmk_action_limit": ""
  "1.4.1.pcmk_monitor_retries": ""
  "1.4.1.pcmk_reboot_timeout": ""
  "1.4.1.power_timeout": ""
  "1.4.2": "true"
