---

expected:
  "1.1.1": "5000"
  "1.1.2": "6000"
  "1.1.3": "20"
  "1.1.4": "60"
  "1.1.5": "10"
  "1.1.6": "udpu"
  "1.1.7": "2"
  "1.1.8": "1"
  "1.2.1": "true"
  "1.2.2.sbd": ""
  "1.2.2.fence_azure_arm": ""
  "1.3.1": "yes"
  "1.3.2": "always"
  "1.3.4": "1"
  "1.3.5": "5"
  "1.3.6": "10"
  "1.4.1.monitor_interval": ""
  "1.4.1.monitor_timeout": ""
  "1.4.1.pcmk_action_limit": ""
  "1.4.1.pcmk_monitor_retries": ""
  "1.4.1.pcmk_reboot_timeout": ""
  "1.4.1.power_timeout": ""
  "1.4.2": "true"
  "2.1.1.resource_stickiness": "1"
  "2.1.1.migration_threshold": "3"
  "2.1.2.monitor_interval": "10"
  "2.1.2.monitor_timeout": "600"
  "2.1.2.start_interval": "0"
  "2.1.2.start_timeout": "600"
  "2.1.2.stop_interval": "0"
  "2.1.2.stop_timeout": "300"
  "2.1.3.master_interval": "60"
  "2.1.3.master_timeout": "700"
  "2.1.3.slave_interval": "61"
  "2.1.3.slave_timeout": "700"
  "2.1.3.start_interval": "0"
  "2.1.3.start_timeout": "3600"
  "2.1.3.stop_interval": "0"
  "2.1.3.stop_timeout": "3600"
  "2.1.3.promote_interval": "0"
  "2.1.3.promote_timeout": "3600"
  "2.1.3.nvpair_PREFER_SITE_TAKEOVER": "true"
  "2.1.3.nvpair_AUTOMATED_REGISTER": "false"
  "2.1.3.nvpair_DUPLICATE_PRIMARY_TIMEOUT": "7200"
  "2.1.4.monitor_interval": "10"
  "2.1.4.monitor_timeout": "20"
  "2.1.5.nvpair_resource_stickiness": "0"
  "2.1.6.rsc_colocation_score": "4000"
  "2.1.6.rsc_colocation_rsc": "g_ip"
  "2.1.6.rsc_colocation_rsc_role": "Started"
  "2.1.6.rsc_colocation_with_rsc": "msl_SAPHana"
  "2.1.6.rsc_colocation_with_rsc_role": "Master"
  "2.1.6.rsc_order_kind": "Optional"
  "2.1.6.rsc_order_first": "cln_SAPHanaTopology"
  "2.1.6.rsc_order_then": "msl_SAPHana"
  "2.1.7.provider": "SAPHanaSR"
  "2.1.7.path": "/usr/share/SAPHanaSR"
  "2.1.7.execution_order": "1"
  "2.1.7.ha_dr_saphanasr": "info"
  "2.2.1": "SLES_SAP"
  "2.2.2": "15.1"
  "2.2.3": "2.0.3"
  "2.2.3.exclude": "2.0.3+20200511.2b248d828"
  "2.2.4": "2.4.5"
  "2.2.5": "1.4.0"
  "2.2.5.exclude": "1.4.0+20190326.c38c5e6"
  "2.2.6": "0.153.0"
  "2.2.7": "3.6.5"
  "2.2.8": "1.0.100.03"
