---

- name: "{{ name }} get the pacemaker version"
  set_fact:
    pacemaker_version: "{{ ansible_facts.packages['pacemaker'][0].version }}"
  delegate_facts: true
  when: "'pacemaker' in ansible_facts.packages"

- name: "{{ name }} compare pacemaker versions across nodes"
  assert:
    that:
      - "{{ groups[item] | map('extract', hostvars) | map(attribute='pacemaker_version') | list | unique | length }} == 1"
    quiet: true
  loop: "{{ group_names }}"
  register: config_updated
  changed_when: config_updated.failed
  when: "pacemaker_version is defined"

- block:
    - name: Post results
      import_role:
        name: post-results
  vars:
    status: "{{ pacemaker_version is defined and config_updated is not changed }}"
