---

- name: set_global_results {{ test_id }}
  set_fact:
    tests: "{{ (tests | default({})) | combine({inventory_hostname: {test_id: {'result': status,'desc': test_desc,'remediation': test_remediation,'mid': test_mid, 'name': test_name} } }, recursive=True) }}"
  delegate_to: localhost
