---

- name: Set Test ID
  set_fact:
    test_id: '1.1.4_runtime'

- name: "{{ test_id }}.check"
  shell: 'corosync-cmapctl | grep "runtime.config.totem.join (u32) = " | sed "s/^.*= //"'
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout != expected['1.1.4']

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
