- hosts: all
  gather_facts: false
  ignore_errors: yes
  become: yes

  vars:
    ara_playbook_labels:
      - test # Do not change the name. It is use in the trento callback call

  tasks:
    - name: require check mode
      fail:
         msg: "Only supported for --check option"
      when:
        - not ansible_check_mode

    - name: Include load_facts
      import_role:
        name: load_facts

    - name: Find checks
      find:
        paths: "{{ playbook_dir}}/roles/checks"
        file_type: directory
      register: checks
      run_once: yes
      delegate_to: localhost

    # Do not change the name. It is use in the trento callback call
    - name: run_checks
      include_role:
        name: "{{ check_item.path }}"
      loop: "{{ checks.files }}"
      loop_control:
        loop_var: check_item # Do not change the name. It is use in the trento callback call
      when: (check_item.path | basename) in cluster_selected_checks_list
