---

- name: Set Test ID
  set_fact:
    test_id: '1.3.4'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.3"
    test_name: "Multiple SBD devices are configured"
    test_desc: "It is recommended to configure {{ expected[test_id] }} SBD devices for production environments"
    test_remediation: | 
      ## Abstract 
      The Multiple SDB Devices configuration is not as recommended for production environments
      ## Remediation
      It is recommended to configure 3 SBD devices for production environments
      ## References 
      <pre> https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#set-up-sbd-device </pre>

- block:
    - import_role:
        name: post-results
        tasks_from: meta
  when:
    - always
