---




- name: Set Test ID
  set_fact:
    test_id: '1.3.1'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.3"
    test_name: "SBD"
    test_desc: "Pacemaker and SBD integration is enabled {{ expected[test_id] }}"
    test_remediation: "ansible"

- name: "{{ test_id }}.result"
  shell: 'grep SBD_PACEMAKER sbd'
  args:
    chdir: "/etc/sysconfig/"
  check_mode: no
  register: config_updated
  changed_when: config_updated != expected[test_id]

- import_role:
    name: cluster_stop
  when:
    - not ansible_check_mode
    - config_updated is changed
    - inventory_hostname == groups.target[0]

- name: "{{ test_id }}.remediate"
  replace:
    path: /etc/sysconfig/sbd
    regexp: '^\s*SBD_PACEMAKER=[a-zA-Z]+?$'
    replace: '{{ expected[test_id] }}'
  when:
    - not ansible_check_mode
    - config_updated is changed


- import_role:
    name: cluster_start
  when:
    - not ansible_check_mode
    - config_updated is changed
    - inventory_hostname == groups.target[0]

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is changed | ternary ('Failed','Passed') }}"
