---

- name: gather facts
  ansible.builtin.setup:
  register: facts_result

- name: load environment variables
  include_vars: "{{ env | default('azure') }}_env.yml"
  delegate_to: localhost
  run_once: true

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: set default value to cluster_selected_checks_list
  set_fact:
    cluster_selected_checks_list: "{{ cluster_selected_checks|default('')|split(',') }}"

- name: debug loaded vars
  debug:
    var: expected
    verbosity: 1
