---

- name: Set Test ID
  set_fact:
    test_id: '1.3.6'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.3"
    test_name: "SBD"
    test_desc: "SBD Timing parameters configured properly {{ expected[test_id] }}"
    test_remediation: |
          ## Remediation
          Make sure you configure your SBD msgwait to 120s as recommended on the best practices.
          
          ## References
          <pre> https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#set-up-sbd-device</pre>


- name: "{{ test_id }}.msgwait_result"
  shell: |
    DEF_MSGWAIT=120
    result_msgwait=${DEF_MSGWAIT}
    sbdarray=$(grep -E '^SBD_DEVICE=' /etc/sysconfig/sbd  | grep -oP 'SBD_DEVICE=\K[^.]+' | sed 's/\"//g')
    IFS=';' sbdarray=( $sbdarray )
    for i in "${sbdarray[@]}"
    do
      msgwait=$(/usr/sbin/sbd -d ${i} dump | grep -oP 'Timeout \(msgwait\)  *: \K\d+')|| echo ""
      if [[ "${msgwait}" -ne "${DEF_MSGWAIT}" ]]; then
        result_msgwait="${msgwait}"
        fi
      done
    echo $result_msgwait
  register: config_updated
  check_mode: no
  changed_when: config_updated.stdout != expected[test_id]

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is changed | ternary ('Failed','Passed') }}"

