---
cloud_type: "vagrant"

expected:
  "1.1.1": "5000"
  "1.1.1_runtime": "5000"
  "1.1.2": "6000"
  "1.1.2_runtime": "6000"
  "1.1.3": "20"
  "1.1.3_runtime": "20"
  "1.1.4": "60"
  "1.1.4_runtime": "60"
  "1.1.5": "10"
  "1.1.5_runtime": "10"
  "1.1.6": ""
  "1.1.7": "2"
  "1.1.8": "1"
  "1.1.8_runtime": "1"
  "1.2.1": "true"
  "1.2.2": ""
  "1.3.1": "SBD_PACEMAKER=yes"
  "1.3.2": "SBD_STARTMODE=always"
  "1.3.3": "enabled"
  "1.3.4": "SBD_COUNT=1"
  "1.3.5": "5"
  "1.3.6": "10"
  "1.4.1.monitor_interval": "3600"
  "1.4.1.monitor_timeout": "120"
  "1.4.1.pcmk_action_limit": "3"
  "1.4.1.pcmk_monitor_retries": "4"
  "1.4.1.pcmk_reboot_timeout": "900"
  "1.4.1.power_timeout": "240"
  "1.4.2": "fence_azure_arm not configured"
  "1.5.1_migration": "5000"
  "1.5.1_resource": "1000"
  "1.5.2_clone": "is_clone"
  "1.5.2_monitor_interval": "10"
  "1.5.2_monitor_timeout": "600"
  "1.5.2_start_interval": "0"
  "1.5.2_start_timeout": "600"
  "1.5.2_stop_interval": "0"
  "1.5.2_stop_timeout": "300"
  "1.5.3_AUTOMATED_REGISTER": "false"
  "1.5.3_DUPLICATE_PRIMARY_TIMEOUT": "7200"
  "1.5.3_PREFER_SITE_TAKEOVER": "true"
  "1.5.3_monitor_master_interval": "60"
  "1.5.3_monitor_master_timeout": "700"
  "1.5.3_monitor_slave_interval": "61"
  "1.5.3_monitor_slave_timeout": "700"
  "1.5.3_msl": "is_msl"
  "1.5.3_promote_interval": "0"
  "1.5.3_promote_timeout": "3600"
  "1.5.3_start_interval": "0"
  "1.5.3_start_timeout": "3600"
  "1.5.3_stop_interval": "0"
  "1.5.4_group": "not_grouped"
  "1.5.4_monitor_interval": "10"
  "1.5.4_monitor_timeout": "20"
  "1.5.5_group": "azure-lb RA is not configured"
  "1.5.5_resource_stickiness": "azure-lb RA is not configured"
  "1.5.6_rsc_colocation_rsc": ""
  "1.5.6_rsc_colocation_rsc_role": "Started"
  "1.5.6_rsc_colocation_score": "2000"
  "1.5.6_rsc_colocation_with_rsc": "msl_SAPHana"
  "1.5.6_rsc_colocation_with_rsc_role": "Master"
  "1.5.6_rsc_order_first": "cln_SAPHanaTopology"
  "1.5.6_rsc_order_kind": "Optional"
  "1.5.6_rsc_order_then": "msl_SAPHana"
  "1.6.1_sidadm": "true"
  "1.6.1_SOK_SITEA": ""
  "1.6.1_SFAIL_SITEA": ""
  "1.6.1_SOK_SITEB": ""
  "1.6.1_SFAIL_SITEB": ""
  "1.6.1_sidadm_all": ""
