---

- name: Set Test ID
  set_fact:
    test_id: '1.3.4'

- name: "{{ test_id }}.check"
  shell: |
    sbdarray=$(grep -E '^SBD_DEVICE=' /etc/sysconfig/sbd  | grep -oP 'SBD_DEVICE=\K[^.]+' | sed 's/\"//g')
    IFS=';' sbdarray=( $sbdarray )
    # convoluted, but normal count method does not work with jinja2
    temp_ar=(${!sbdarray[@]});  device_count=`expr ${temp_ar[-1]} + 1`
    echo "$device_count"
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout != expected[test_id]

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"


