- block:
    - import_role:
        name: post-metadata
        tasks_from: store
  vars:
    id: 1.3.4
    name: Multiple SBD devices are configured
    group: SBD
    labels: generic
    description: |
      Test if multiple SBD devices are configured
    remediation: |
      ## Abstract
      It is recommended to configure 3 SBD devices for production environments.
      
      ## References
      -  https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#set-up-sbd-device
    implementation: "{{ lookup('file', 'roles/'+id+'/tasks/main.yml') }}"
