---

- name: Set Test ID
  set_fact:
    test_id: '2.2.5'

- name: "{{ test_id }}.check"
  shell: |
    # Check the sbd version IS
    # If not installed, exit with error
    rpm -q --qf "%{VERSION}\n" sbd || exit 2
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout is version(expected[test_id], '<')
  failed_when: config_updated.rc > 1

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
