---

- name: Set Test ID
  set_fact:
    test_id: '1.1.8'
    key_name: 'two_node'

- name: "{{ test_id }}.check"
  lineinfile:
    path: /etc/corosync/corosync.conf
    regexp: '^(\s+){{ key_name }}:'
    line: '	{{ key_name }}: {{ expected[test_id] }}'
    insertafter: 'quorum {'
  register: config_updated
  when: ansible_check_mode

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
