---

- name: "{{ name }}.check"
  assert:
    that:
      - "{{ groups[item] | map('extract', hostvars) | map(attribute='ansible_distribution_version') | list | unique | length }} == 1"
    quiet: true
  loop: "{{ group_names }}"
  register: config_updated
  changed_when: config_updated.failed

- block:
    - name: Post results
      import_role:
        name: post-results
  vars:
    status: "{{ config_updated is not changed }}"
