---

- name: Set Test ID
  set_fact:
    test_id: '1.2.1'

- name: "{{ test_id }}.result"
  shell: 'crm_attribute -t crm_config -G -n stonith-enabled --quiet'
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout != expected[test_id]

- name: "{{ test_id }}.remediate"
  shell: 'crm configure property stonith-enabled=true'
  when:
    - config_updated is changed
    - not ansible_check_mode

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is changed | ternary ('false','true') }}"
