---

- name: "{{ name }} get the SAPHanaSR version"
  set_fact:
    saphanasr_version: "{{ ansible_facts.packages['SAPHanaSR'][0].version }}"
  delegate_facts: true
  when: "'SAPHanaSR' in ansible_facts.packages"

- name: "{{ name }} compare SAPHanaSR versions across nodes"
  assert:
    that:
      - "{{ groups[item] | map('extract', hostvars) | map(attribute='saphanasr_version') | list | unique | length }} == 1"
    quiet: true
  loop: "{{ group_names }}"
  register: config_updated
  changed_when: config_updated.failed
  when: "saphanasr_version is defined"

- block:
    - name: Post results
      import_role:
        name: post-results
  vars:
    status: "{{ saphanasr_version is defined and config_updated is not changed }}"
