---

id: 1.1.9.runtime
name: Corosync has at least 2 configured rings (runtime)
group: Corosync
labels: generic
description: |
  Test if corosync has at least 2 rings configured during runtime
remediation: |
  ## Abstract
  It is strongly recommended to add a second ring to the corosync communication.

  ## References
  - section 9.1.3 in https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-adapting-the-corosync-and-sbd-configuration
implementation: "{{ lookup('file', 'roles/checks/'+id+'/tasks/main.yml') }}"
on_failure: warning

# check external_id. This value must not be changed over the life of this check
external_id: 32CFC6
